# Generated by Django 3.2.5 on 2022-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
