# Generated by Django 3.2.5 on 2022-02-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_explorer', '0003_auto_20220211_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
