# Generated by Django 3.2.5 on 2022-02-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalidator',
            name='email',
            field=models.EmailField(max_length=500, unique=True),
        ),
    ]
