# Generated by Django 3.2.5 on 2022-02-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_web_vitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corewebvitals',
            name='device',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
