# Generated by Django 3.2.5 on 2022-02-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_web_vitals', '0003_alter_corewebvitals_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='corewebvitals',
            name='cls',
            field=models.FloatField(null=True),
        ),
    ]
