# Generated by Django 3.2.5 on 2022-02-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_web_vitals', '0004_corewebvitals_cls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corewebvitals',
            name='cls',
        ),
        migrations.RemoveField(
            model_name='corewebvitals',
            name='device',
        ),
        migrations.RemoveField(
            model_name='corewebvitals',
            name='fcp',
        ),
        migrations.RemoveField(
            model_name='corewebvitals',
            name='lcp',
        ),
        migrations.RemoveField(
            model_name='corewebvitals',
            name='score',
        ),
        migrations.RemoveField(
            model_name='corewebvitals',
            name='si',
        ),
        migrations.RemoveField(
            model_name='corewebvitals',
            name='tbt',
        ),
        migrations.RemoveField(
            model_name='corewebvitals',
            name='tti',
        ),
        migrations.AddField(
            model_name='corewebvitals',
            name='data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
