# Generated by Django 3.2.5 on 2022-02-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_web_vitals', '0005_auto_20220224_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='corewebvitals',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corewebvitals',
            name='device',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
